/**
 * Passport Color System
 *
 * Maps nationalities to their real passport cover colors.
 * Most passports fall into 4 color categories: Blue, Red/Burgundy, Green, Black
 */

export interface PassportColorScheme {
  // Main cover gradient
  from: string;
  via: string;
  to: string;
  // Accent colors for details
  accent: string;
  accentLight: string;
  // Text colors
  text: string;
  textMuted: string;
}

// Predefined color schemes
const PASSPORT_SCHEMES = {
  // Blue passports (USA, Canada, Australia, Israel, etc.)
  blue: {
    from: 'from-blue-800',
    via: 'via-blue-900',
    to: 'to-blue-950',
    accent: 'border-blue-400/50',
    accentLight: 'bg-blue-400/40',
    text: 'text-blue-100',
    textMuted: 'text-blue-200/60',
  },
  // Burgundy/Wine red passports (EU, UK, China, etc.)
  burgundy: {
    from: 'from-rose-800',
    via: 'via-rose-900',
    to: 'to-rose-950',
    accent: 'border-rose-400/50',
    accentLight: 'bg-rose-400/40',
    text: 'text-rose-100',
    textMuted: 'text-rose-200/60',
  },
  // Green passports (Muslim countries, ECOWAS, etc.)
  green: {
    from: 'from-emerald-800',
    via: 'via-emerald-900',
    to: 'to-emerald-950',
    accent: 'border-emerald-400/50',
    accentLight: 'bg-emerald-400/40',
    text: 'text-emerald-100',
    textMuted: 'text-emerald-200/60',
  },
  // Black passports (New Zealand, some African countries, diplomatic)
  black: {
    from: 'from-slate-800',
    via: 'via-slate-900',
    to: 'to-slate-950',
    accent: 'border-slate-400/50',
    accentLight: 'bg-slate-400/40',
    text: 'text-slate-100',
    textMuted: 'text-slate-200/60',
  },
  // Red passports (Switzerland, Japan, some Asian countries)
  red: {
    from: 'from-red-700',
    via: 'via-red-800',
    to: 'to-red-900',
    accent: 'border-red-300/50',
    accentLight: 'bg-red-300/40',
    text: 'text-red-100',
    textMuted: 'text-red-200/60',
  },
} as const;

// Map nationalities to color schemes
const NATIONALITY_COLORS: Record<string, keyof typeof PASSPORT_SCHEMES> = {
  // Blue passports
  'American': 'blue',
  'United States': 'blue',
  'USA': 'blue',
  'Canadian': 'blue',
  'Canada': 'blue',
  'Australian': 'blue',
  'Australia': 'blue',
  'Israeli': 'blue',
  'Israel': 'blue',
  'Argentine': 'blue',
  'Argentina': 'blue',
  'Brazilian': 'blue',
  'Brazil': 'blue',
  'Uruguayan': 'blue',
  'Paraguay': 'blue',
  'Venezuelan': 'blue',
  'Costa Rican': 'blue',
  'Honduran': 'blue',
  'Guatemalan': 'blue',
  'Salvadoran': 'blue',
  'Nicaraguan': 'blue',
  'Panamanian': 'blue',
  'Cuban': 'blue',
  'Caribbean': 'blue',
  'Jamaican': 'blue',
  'Bahamian': 'blue',
  'Syrian': 'blue',
  'Iraqi': 'blue',
  'Lebanese': 'blue',
  'Cambodian': 'blue',
  'Filipino': 'blue',
  'Philippines': 'blue',
  'Taiwanese': 'blue',
  'Taiwan': 'blue',
  'South Korean': 'blue',
  'Korean': 'blue',
  'Libyan': 'blue',

  // Burgundy/Wine red passports
  'British': 'burgundy',
  'UK': 'burgundy',
  'United Kingdom': 'burgundy',
  'Chinese': 'burgundy',
  'China': 'burgundy',
  'German': 'burgundy',
  'Germany': 'burgundy',
  'French': 'burgundy',
  'France': 'burgundy',
  'Italian': 'burgundy',
  'Italy': 'burgundy',
  'Spanish': 'burgundy',
  'Spain': 'burgundy',
  'Portuguese': 'burgundy',
  'Portugal': 'burgundy',
  'Dutch': 'burgundy',
  'Netherlands': 'burgundy',
  'Belgian': 'burgundy',
  'Belgium': 'burgundy',
  'Austrian': 'burgundy',
  'Austria': 'burgundy',
  'Greek': 'burgundy',
  'Greece': 'burgundy',
  'Polish': 'burgundy',
  'Poland': 'burgundy',
  'Romanian': 'burgundy',
  'Romania': 'burgundy',
  'Bulgarian': 'burgundy',
  'Bulgaria': 'burgundy',
  'Croatian': 'burgundy',
  'Croatia': 'burgundy',
  'Czech': 'burgundy',
  'Czech Republic': 'burgundy',
  'Slovak': 'burgundy',
  'Slovakia': 'burgundy',
  'Hungarian': 'burgundy',
  'Hungary': 'burgundy',
  'Slovenian': 'burgundy',
  'Slovenia': 'burgundy',
  'Estonian': 'burgundy',
  'Latvia': 'burgundy',
  'Lithuanian': 'burgundy',
  'Lithuania': 'burgundy',
  'Finnish': 'burgundy',
  'Finland': 'burgundy',
  'Swedish': 'burgundy',
  'Sweden': 'burgundy',
  'Danish': 'burgundy',
  'Denmark': 'burgundy',
  'Norwegian': 'burgundy',
  'Norway': 'burgundy',
  'Icelandic': 'burgundy',
  'Irish': 'burgundy',
  'Ireland': 'burgundy',
  'Luxembourg': 'burgundy',
  'Maltese': 'burgundy',
  'Cypriot': 'burgundy',
  'Turkish': 'burgundy',
  'Turkey': 'burgundy',
  'Russian': 'burgundy',
  'Russia': 'burgundy',
  'Ukrainian': 'burgundy',
  'Ukraine': 'burgundy',
  'Georgian': 'burgundy',
  'Georgia': 'burgundy',
  'Armenian': 'burgundy',
  'Belarus': 'burgundy',
  'Moldovan': 'burgundy',
  'Serbian': 'burgundy',
  'Serbia': 'burgundy',
  'Albanian': 'burgundy',
  'North Macedonian': 'burgundy',
  'Bosnian': 'burgundy',
  'Montenegrin': 'burgundy',
  'Kosovar': 'burgundy',
  'Indian': 'burgundy',
  'India': 'burgundy',
  'Singaporean': 'burgundy',
  'Singapore': 'burgundy',
  'Thai': 'burgundy',
  'Thailand': 'burgundy',
  'Vietnamese': 'burgundy',
  'Vietnam': 'burgundy',
  'Laotian': 'burgundy',
  'Colombian': 'burgundy',
  'Ecuadorian': 'burgundy',
  'Peru': 'red',
  'Bolivian': 'burgundy',
  'Chilean': 'burgundy',

  // Green passports
  'Saudi Arabian': 'green',
  'Saudi Arabia': 'green',
  'Pakistani': 'green',
  'Pakistan': 'green',
  'Moroccan': 'green',
  'Morocco': 'green',
  'Egyptian': 'green',
  'Egypt': 'green',
  'Algerian': 'green',
  'Algeria': 'green',
  'Tunisian': 'green',
  'Tunisia': 'green',
  'Nigerian': 'green',
  'Nigeria': 'green',
  'Ghanaian': 'green',
  'Ghana': 'green',
  'Senegalese': 'green',
  'Senegal': 'green',
  'Ivorian': 'green',
  "Côte d'Ivoire": 'green',
  'Burkina Faso': 'green',
  'Malian': 'green',
  'Mali': 'green',
  'Niger': 'green',
  'Guinean': 'green',
  'Cameroonian': 'green',
  'Cameroon': 'green',
  'Indonesian': 'green',
  'Indonesia': 'green',
  'Malaysian': 'green',
  'Malaysia': 'green',
  'Bangladeshi': 'green',
  'Bangladesh': 'green',
  'Afghan': 'green',
  'Afghanistan': 'green',
  'Iranian': 'green',
  'Iran': 'green',
  'UAE': 'green',
  'Emirati': 'green',
  'Qatari': 'green',
  'Qatar': 'green',
  'Kuwaiti': 'green',
  'Kuwait': 'green',
  'Omani': 'green',
  'Oman': 'green',
  'Bahraini': 'green',
  'Bahrain': 'green',
  'Yemeni': 'green',
  'Yemen': 'green',
  'Jordanian': 'green',
  'Jordan': 'green',
  'Uzbek': 'green',
  'Uzbekistan': 'green',
  'Kazakh': 'green',
  'Kazakhstan': 'green',
  'Turkmen': 'green',
  'Turkmenistan': 'green',
  'Kyrgyz': 'green',
  'Kyrgyzstan': 'green',
  'Tajik': 'green',
  'Tajikistan': 'green',
  'Azerbaijani': 'green',
  'Azerbaijan': 'green',
  'South African': 'green',
  'South Africa': 'green',
  'Kenyan': 'green',
  'Kenya': 'green',
  'Ethiopian': 'green',
  'Ethiopia': 'green',
  'Tanzanian': 'green',
  'Tanzania': 'green',
  'Ugandan': 'green',
  'Uganda': 'green',
  'Rwandan': 'green',
  'Rwanda': 'green',
  'Sudanese': 'green',
  'Sudan': 'green',
  'Somali': 'green',
  'Somalia': 'green',
  'Eritrean': 'green',
  'Eritrea': 'green',
  'Djiboutian': 'green',
  'Mauritian': 'green',
  'Mauritius': 'green',
  'Zambian': 'green',
  'Zimbabwean': 'green',
  'Mozambican': 'green',
  'Angolan': 'green',
  'Congolese': 'green',
  'Maldivian': 'green',
  'Maldives': 'green',
  'Bruneian': 'green',
  'Brunei': 'green',

  // Red passports
  'Japanese': 'red',
  'Japan': 'red',
  'Swiss': 'red',
  'Switzerland': 'red',
  'Peruvian': 'red',
  'Andorran': 'red',
  'Liechtenstein': 'red',
  'Mongolian': 'red',
  'North Korean': 'red',
  'Sri Lankan': 'red',
  'Sri Lanka': 'red',
  'Nepalese': 'red',
  'Nepal': 'red',
  'Bhutanese': 'red',
  'Bhutan': 'red',
  'Myanmar': 'red',
  'Burmese': 'red',

  // Black passports
  'New Zealand': 'black',
  'New Zealander': 'black',
  'Mexican': 'black',
  'Mexico': 'black',
  'Malawian': 'black',
  'Malawi': 'black',
  'Botswanan': 'black',
  'Botswana': 'black',
  'Gabonese': 'black',
  'Gabon': 'black',
  'Congolese (DRC)': 'black',
  'Zambia': 'black',
  'Dominican': 'black',
  'Dominican Republic': 'black',
  'Trinidad and Tobago': 'black',
  'Trinidadian': 'black',
  'Haitian': 'black',
  'Haiti': 'black',
  'Barbadian': 'black',
  'Barbados': 'black',
  'Antigua': 'black',
  'Burundian': 'black',
  'Burundi': 'black',
  'Central African': 'black',
  'Chadian': 'black',
  'Chad': 'black',
  'Lesotho': 'black',
  'Swaziland': 'black',
  'Eswatini': 'black',
  'Namibian': 'black',
  'Namibia': 'black',
};

/**
 * Get passport color scheme based on nationality
 */
export function getPassportColorScheme(nationality: string): PassportColorScheme {
  const colorKey = NATIONALITY_COLORS[nationality] || 'burgundy'; // Default to burgundy
  return PASSPORT_SCHEMES[colorKey];
}

/**
 * Get passport gradient classes for Tailwind
 */
export function getPassportGradient(nationality: string): string {
  const scheme = getPassportColorScheme(nationality);
  return `bg-gradient-to-br ${scheme.from} ${scheme.via} ${scheme.to}`;
}

/**
 * Get passport book colors (for the icon)
 */
export function getPassportBookColors(nationality: string) {
  const colorKey = NATIONALITY_COLORS[nationality] || 'burgundy';

  const bookColors = {
    blue: {
      gradient: 'from-blue-600 to-blue-700',
      spine: 'from-blue-800/40',
      border: 'border-blue-400/30',
      emblem: 'border-blue-300/50',
      emblemInner: 'bg-blue-300/40',
      pages: 'bg-blue-100/20',
    },
    burgundy: {
      gradient: 'from-rose-700 to-rose-800',
      spine: 'from-rose-900/40',
      border: 'border-rose-400/30',
      emblem: 'border-rose-300/50',
      emblemInner: 'bg-rose-300/40',
      pages: 'bg-rose-100/20',
    },
    green: {
      gradient: 'from-emerald-700 to-emerald-800',
      spine: 'from-emerald-900/40',
      border: 'border-emerald-400/30',
      emblem: 'border-emerald-300/50',
      emblemInner: 'bg-emerald-300/40',
      pages: 'bg-emerald-100/20',
    },
    black: {
      gradient: 'from-slate-700 to-slate-800',
      spine: 'from-slate-900/40',
      border: 'border-slate-400/30',
      emblem: 'border-slate-300/50',
      emblemInner: 'bg-slate-300/40',
      pages: 'bg-slate-100/20',
    },
    red: {
      gradient: 'from-red-600 to-red-700',
      spine: 'from-red-800/40',
      border: 'border-red-300/30',
      emblem: 'border-red-200/50',
      emblemInner: 'bg-red-200/40',
      pages: 'bg-red-100/20',
    },
  };

  return bookColors[colorKey];
}
